#!/bin/bash
# /etc/init.d/air
#

function start_air {
  CONTAINER_ENV=prod /aircloak/air/etcd/container.sh ensure_started
  CONTAINER_ENV=prod /aircloak/air/router/container.sh ensure_latest_version_started
  CONTAINER_ENV=prod /aircloak/air/balancer/container.sh ensure_latest_version_started
}

function stop_air {
  CONTAINER_ENV=prod /aircloak/air/balancer/container.sh stop
  CONTAINER_ENV=prod /aircloak/air/router/container.sh stop
  CONTAINER_ENV=prod /aircloak/air/etcd/container.sh stop
}

case "$1" in
  start)
    start_air
    ;;
  stop)
    stop_air
    ;;
  *)
    echo "Usage: ${BASH_SOURCE[0]} {start|stop}"
    exit 1
    ;;
esac

exit 0
