language: erlang
otp_release:
   - 17.4
   # Travis doesn't yet support 17.5.
   # Support will land with their June update,
   # at which point we should test using 17.5
   # instead of 17.4
   # - 17.5
cache:
  directories:
  - frontend/vendor/bundle
  - $HOME/air-plt
addons:
  postgresql: "9.4"
before_install:
  # Check last 100 commits for valid signatures. Number 100 is chosen in a hacky
  # manner, assuming no reasonable PR will be that large.
  - git log --pretty="format:%H$t%aN$t%s$t%G?" -n 100 | grep -v "${t}G$"
  - sudo hostname "$(hostname).local"
  - sudo apt-get update -qq
  - sudo apt-get install -y protobuf-c-compiler liblua5.1-0-dev libprotobuf-c0-dev protobuf-compiler
  - rvm install 2.0.0
  - curl -L  https://github.com/coreos/etcd/releases/download/v2.0.11/etcd-v2.0.11-linux-amd64.tar.gz -o etcd-v2.0.11-linux-amd64.tar.gz && tar xzvf etcd-v2.0.11-linux-amd64.tar.gz
  - etcd-v2.0.11-linux-amd64/etcd -addr 127.0.0.1:4003 &
before_script:
  - etcd/config_travis.sh
  - db/init_db.sh
script:
  - cd frontend && bundle install --path vendor/bundle && RAILS_ENV=test bundle exec rake db:migrate && bundle exec rake && cd ..
  - cd backend && make all && make doc && make test && ./run_dialyzer.sh && cd ..
source_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdk52V1hEZHBhQ2dWbUJNd2x6amVDZyt0U20wRnVMbHkxTTJGclExTk15cGx3RWhsCmRBYXFqUjVMV25PQVJYM2NVcy8wUGVnWUFrQmxlMFptY253ZzVxT2diZ0krRkVEeklsR0NWcU9iQUdtNG9UUVAKa1V1dUhzYng1d25kbENLWFNKbzU3aEpXUlg3bHN0NHhtb2kva01UYWFiZlpDamUyOXNoR2dGZGg2K0JRM242dApFelFOQ243WlRRczV1MXJXd2tjeS9VWE83VFdzK0tMa3o5Si9jZVAzejJLMGtQaFFMQzdtTHhPSXpkRmpobE9uCjFNTDRwNjQ5aVYzTUgzdGZwSGFyc3JidnBQMXd6S253ZTZOSElpeXJ0SExOR1F5TEZKRHBEdDZadStoTzhEbXcKOUhrSjdvajQ2MnZjWFVpRmY4aVBSL1g5Nlh2ZFZNVWJLUTlZalFJREFRQUJBb0lCQUJzRUc2ci9aajIzRmplMQo3d3FDNFFoeGE2bXM1TmVpOTdGSFlTcjdMeUwxbXE2aDdKbG5acmhmTUFwVllYRVBheGdSbFcvUnByV1R2ckNlCnhvTDBETVRSZlY2ZlJZQWlObVdmWVZUQmZLZlhkOGpmcUtaeFBBdzlDMWV3aXBqcFJkamw3d21HWi83ekF5ck8KTEN4ZUNZRk5GNjF0MWtkbTV1NXdnZDFVSXJiYUZkRnE0S2g0aCtyajZub3ROWHlhcStlbUEyNitwd0Z0VjhoUQo4alArcm9OcnFCQ0hsOXVsQko3a0VIaWFIallZOFY2MElYOXVQWDZ4aWhhMHE2dTFMQXZ4WlVEQ2krb3gxU2UrCjg5UFV0UVpwQnFERDVJekdNNGN4cFR0UnNubTdOUSsrb0F4c3doaUZ6RkI0UlN3MEV4bWYxUnRhTmlEZkFzNmkKK2htb0x1VUNnWUVBNlpSRzVJeGJHQ2pZbTBGNkRUUXlyVjVoYm9GWHNEdDRrNkQ5OGZuQ1l1RWJGSy9ySmxTOQpYMGtmY1QwOHIyVDB0aGxXZXJxMmZ3VDY5dllQdWIxRkhjRGpTZ3pHYUpVazFYN2Z1cUN3NURTMTFQVlN3N25qCnA4MDJGbXhnc2o4cndSRHVNZ253KytLRzI2TUZFZHRaeFpjczgzOElHMG9RYk9SUDY4TXozTk1DZ1lFQXp2eWwKNGJpbVVjUm9rdWxxUG1zK3dmaWNvMWNsVUVEejN0VmZJM2lSYkExdlhObllKL0FoUS9UUmZQUmoxck5MdUl5WQpycUVXWExnM2poeTMrKzFlK25PYk5vM1ZUOHplcU1BUXVsTm93OGY0aEdVM3BmVU5oSzE2R3Nlb2V4OXBPRXRpCkhJQmxUbnVrRENCOWt4YmlQQ0tHOGRtMjBtWjdRakVBd2JlTkdSOENnWUJUQXRKTENTS2FySEdHZzdlWGw3Um0KN3NMYm5mWUcrS3U2YzUyc2NHSEgrRTVDaE42aUtiMS9icUpSQVQxZTdCY1gzRnRpbEphay82VWRQWWVMTUJ1dgpIa3pvbFMreUhVY1E1TjBvRzFHaVdLVkNnTWtnTENFZkVvd2xYZkRqaUJYSnNIV21yT2ZLN00rV29SSDlMYUp5CjJXNHRQemtuVWFRU3Z2VTBTWlJWNXdLQmdRRExBUmRnTGsxUTNLVURrVkhXTGpDNjVTNGJOUmt2Z01TdHcrOHYKUnN5NWdPTzcyUndhNzNSd3hlZS8rYUVCclkrU1RMSmljek1QZE0xbjM5ckNocWdrVXNYajEyOWllTGZZSWFkRwpWdy9sRkhjMHdtQzFyNFcybnIybkRqSzdycTd2dTE5YVBNTWZHanhtZUdjd243ejY1WkljR1Q4cFU4R0h4YS9NClRrMWdXUUtCZ0UvRjdHL2dUSHoxYnRUeDRPVDJpdWpDbXJ2bXNwMzVRQk9IWmpTYXBERWNVTWcrd05pRUdIL3UKNTE3NlhCKzJRT0taVlhvWFIxU0g1NTFNMmdpU1JpQitQUGx0SmErNW1tcHVZVXpSSHNYL1FwMkFTbkoxNUd2ZQpraC9iZW45YTNIdnpPVE9MMCtLTndiT05DMW9ReXc4WHU2SzdCakZaa3lnQzQ2S01adUZsCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
