sudo: false
language: elixir
elixir:
  - 1.3.2
otp_release:
  - 18.2.1
env:
  global:
    - MIX_HOME=$(pwd)/.mix
    - COMPILER=g++-4.8
    - CXX="g++-4.8"
    - CC="gcc-4.8"
cache:
  directories:
  - common/elixir/deps
  - common/elixir/_build
  - air/deps
  - air/_build
  - air/node_modules
  - air/api_docs/vendor/bundle
  - .mix
  - cloak/deps
  - cloak/_build
  - bom/deps
  - bom/_build
addons:
  postgresql: "9.4"
  mariadb: "10.0"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - protobuf-compiler
    - protobuf-c-compiler
    - liblua5.1-0-dev
    - libprotobuf-c0-dev
    - jq
    - gcc-4.8
    - g++-4.8
    - unixodbc
    - odbc-postgresql
  hosts:
    - travis.aircloak.local
before_install:
  - psql -c "CREATE DATABASE cloaktest1 ENCODING 'UTF8';" -U postgres
  - mysql -e "CREATE DATABASE cloaktest1 DEFAULT CHARACTER SET utf8;" -u root
  - odbcinst -i -s -h -f cloak/priv/odbc/odbc.ini
  - nvm install node
install:
  - mkdir -p $MIX_HOME
  - mix local.hex --force
  - mix local.rebar --force
before_script:
  # common/elixir
  - cd common/elixir
  - mix deps.get
  - mix compile --warnings-as-errors
  - MIX_ENV=test make all
  - cd ../..
  # air and insights
  - air/set_travis_config.sh
  - air/db/init_db.sh
  - cd air
  - make deps
  - mix compile --warnings-as-errors
  - MIX_ENV=test mix compile --warnings-as-errors
  - MIX_ENV=prod mix compile --warnings-as-errors
  - MIX_ENV=test make recreate_db
  - cd ../..
  # cloak
  - cd cloak
  - make deps
  - mix compile --warnings-as-errors
  - MIX_ENV=test make all
  - cd ..
  # bom
  - cd bom
  - make deps
  - mix compile --warnings-as-errors
  - cd ..
script:
  # common/elixir
  - cd common/elixir
  - make docs
  - make lint
  - make check_dependent_apps
  - make test
  - make dialyze
  - cd ../..
  # insights
  - cd air
  - make docs
  - make lint
  - make check_dependent_apps
  - make test
  - make dialyze
  - cd ../..
  # cloak
  - cd cloak
  - make docs
  - make lint
  - make check_dependent_apps
  - make test
  - make dialyze
  - make proper-extended
  - cd ..
  # bom
  - cd bom
  - make docs
  - make lint
  - make check_dependent_apps
  - make test
  - make dialyze
  - mix bom --elixir ../cloak/deps --elixir ../air/deps --node ../air/node_modules bom.json
  - cd ..
source_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdk52V1hEZHBhQ2dWbUJNd2x6amVDZyt0U20wRnVMbHkxTTJGclExTk15cGx3RWhsCmRBYXFqUjVMV25PQVJYM2NVcy8wUGVnWUFrQmxlMFptY253ZzVxT2diZ0krRkVEeklsR0NWcU9iQUdtNG9UUVAKa1V1dUhzYng1d25kbENLWFNKbzU3aEpXUlg3bHN0NHhtb2kva01UYWFiZlpDamUyOXNoR2dGZGg2K0JRM242dApFelFOQ243WlRRczV1MXJXd2tjeS9VWE83VFdzK0tMa3o5Si9jZVAzejJLMGtQaFFMQzdtTHhPSXpkRmpobE9uCjFNTDRwNjQ5aVYzTUgzdGZwSGFyc3JidnBQMXd6S253ZTZOSElpeXJ0SExOR1F5TEZKRHBEdDZadStoTzhEbXcKOUhrSjdvajQ2MnZjWFVpRmY4aVBSL1g5Nlh2ZFZNVWJLUTlZalFJREFRQUJBb0lCQUJzRUc2ci9aajIzRmplMQo3d3FDNFFoeGE2bXM1TmVpOTdGSFlTcjdMeUwxbXE2aDdKbG5acmhmTUFwVllYRVBheGdSbFcvUnByV1R2ckNlCnhvTDBETVRSZlY2ZlJZQWlObVdmWVZUQmZLZlhkOGpmcUtaeFBBdzlDMWV3aXBqcFJkamw3d21HWi83ekF5ck8KTEN4ZUNZRk5GNjF0MWtkbTV1NXdnZDFVSXJiYUZkRnE0S2g0aCtyajZub3ROWHlhcStlbUEyNitwd0Z0VjhoUQo4alArcm9OcnFCQ0hsOXVsQko3a0VIaWFIallZOFY2MElYOXVQWDZ4aWhhMHE2dTFMQXZ4WlVEQ2krb3gxU2UrCjg5UFV0UVpwQnFERDVJekdNNGN4cFR0UnNubTdOUSsrb0F4c3doaUZ6RkI0UlN3MEV4bWYxUnRhTmlEZkFzNmkKK2htb0x1VUNnWUVBNlpSRzVJeGJHQ2pZbTBGNkRUUXlyVjVoYm9GWHNEdDRrNkQ5OGZuQ1l1RWJGSy9ySmxTOQpYMGtmY1QwOHIyVDB0aGxXZXJxMmZ3VDY5dllQdWIxRkhjRGpTZ3pHYUpVazFYN2Z1cUN3NURTMTFQVlN3N25qCnA4MDJGbXhnc2o4cndSRHVNZ253KytLRzI2TUZFZHRaeFpjczgzOElHMG9RYk9SUDY4TXozTk1DZ1lFQXp2eWwKNGJpbVVjUm9rdWxxUG1zK3dmaWNvMWNsVUVEejN0VmZJM2lSYkExdlhObllKL0FoUS9UUmZQUmoxck5MdUl5WQpycUVXWExnM2poeTMrKzFlK25PYk5vM1ZUOHplcU1BUXVsTm93OGY0aEdVM3BmVU5oSzE2R3Nlb2V4OXBPRXRpCkhJQmxUbnVrRENCOWt4YmlQQ0tHOGRtMjBtWjdRakVBd2JlTkdSOENnWUJUQXRKTENTS2FySEdHZzdlWGw3Um0KN3NMYm5mWUcrS3U2YzUyc2NHSEgrRTVDaE42aUtiMS9icUpSQVQxZTdCY1gzRnRpbEphay82VWRQWWVMTUJ1dgpIa3pvbFMreUhVY1E1TjBvRzFHaVdLVkNnTWtnTENFZkVvd2xYZkRqaUJYSnNIV21yT2ZLN00rV29SSDlMYUp5CjJXNHRQemtuVWFRU3Z2VTBTWlJWNXdLQmdRRExBUmRnTGsxUTNLVURrVkhXTGpDNjVTNGJOUmt2Z01TdHcrOHYKUnN5NWdPTzcyUndhNzNSd3hlZS8rYUVCclkrU1RMSmljek1QZE0xbjM5ckNocWdrVXNYajEyOWllTGZZSWFkRwpWdy9sRkhjMHdtQzFyNFcybnIybkRqSzdycTd2dTE5YVBNTWZHanhtZUdjd243ejY1WkljR1Q4cFU4R0h4YS9NClRrMWdXUUtCZ0UvRjdHL2dUSHoxYnRUeDRPVDJpdWpDbXJ2bXNwMzVRQk9IWmpTYXBERWNVTWcrd05pRUdIL3UKNTE3NlhCKzJRT0taVlhvWFIxU0g1NTFNMmdpU1JpQitQUGx0SmErNW1tcHVZVXpSSHNYL1FwMkFTbkoxNUd2ZQpraC9iZW45YTNIdnpPVE9MMCtLTndiT05DMW9ReXc4WHU2SzdCakZaa3lnQzQ2S01adUZsCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
