<% require './lib/aircloak_config' %>

development:
  adapter: postgresql
  encoding: unicode
  host: <%= Conf.get("/settings/air/db/host") %>
  port: <%= Conf.get("/settings/air/db/port") %>
  username: <%= Conf.get("/settings/air/db/username") %>
  password: <%= Conf.get("/settings/air/db/password") %>
  database: <%= Conf.get("/settings/air/db/database") %>
  pool: 4

production:
  adapter: postgresql
  encoding: unicode
  host: <%= Conf.get("/settings/air/db/host") %>
  port: <%= Conf.get("/settings/air/db/port") %>
  username: <%= Conf.get("/settings/air/db/username") %>
  password: <%= Conf.get("/settings/air/db/password") %>
  database: <%= Conf.get("/settings/air/db/database") %>
  pool: 4

test:
  adapter: postgresql
  encoding: unicode
  host: <%= Conf.get("/settings/air/db/host") %>
  port: <%= Conf.get("/settings/air/db/port") %>
  username: <%= Conf.get("/settings/air/db/username") %>
  password: <%= Conf.get("/settings/air/db/password") %>
  database: <%= Conf.get("/settings/air/db/database") %>
  pool: 4

precompile:
  adapter: sqlite3
  database: db/precompile.sqlite3
  pool: 5
  timeout: 5000
