defaults: &defaults
  installation:
    global: true
  task:
    return_protocol: https
    return_host: hello.aircloak.com
    return_port: 443
  build_server:
    host: build.aircloak.com
  cloak:
    protocol: https
    port: 443
  results:
    max_per_query: 4
  local_sandbox:
    endpoint: http://127.0.0.1:11000

development:
  <<: *defaults
  # empty means send to default cloak-core URL
  publish_url: "" # http://127.0.0.1:1080/publish
  airpub_shared_secret: "well-known secret"
  airpub_ws_subscribe: ws://127.0.0.1:1080/subscribe/ws

production:
  <<: *defaults
  # empty means send to default cloak-core URL
  publish_url: "" # https://pub.aircloak.com/publish
  # airpub_shared_secret is set in settings.local.yml
  airpub_ws_subscribe: wss://pub.aircloak.com/subscribe/ws

test: &testing
  <<: *defaults
  task:
    return_protocol: http
    return_host: localhost
    return_port: 3000
  build_server:
    host: localhost
  private_key_password: test_password
  github_oauth_token: "273c13ccc918a992618a503df7dadfe06f70b3f5"
  secret_key_base: 'random-secret'
  airpub_shared_secret: "well-known secret"
