FROM debian:jessie
MAINTAINER Sebastian Probst Eide <sebastian@aircloak.com>


## ------------------------------------------------------------------
## Some basic setup of the image
## ------------------------------------------------------------------

RUN apt-get update
RUN apt-get install build-essential -y
RUN apt-get install libssl-dev -y
RUN apt-get install git curl -y
RUN apt-get install libncurses5-dev -y


## ------------------------------------------------------------------
## Get erlang installed
## ------------------------------------------------------------------

RUN curl -L -O http://www.erlang.org/download/otp_src_17.5.tar.gz
RUN mkdir -p /tmp/download
RUN mv /otp_src_17.5.tar.gz /tmp/download/otp.tar.gz

WORKDIR /tmp/download
RUN tar -zxvf otp.tar.gz
RUN rm otp.tar.gz

WORKDIR /tmp/download/otp_src_17.5
RUN ./configure --disable-hipe
RUN make
RUN make install


## ------------------------------------------------------------------
## Get dependencies needed on the build system
## ------------------------------------------------------------------

# We need protocol buffer support to communicate
# with the sandboxes
RUN apt-get install libprotobuf-c-dev -y
RUN apt-get install protobuf-c-compiler -y

# Lua is needed by the sandbox in cloak-core
RUN apt-get install liblua5.1-0-dev -y


## ------------------------------------------------------------------
## Configure user and get app in place
## ------------------------------------------------------------------

# User under which the app will run.
# Confd will also run as the same user
RUN useradd --create-home --shell /bin/bash deployer

RUN mkdir -p /aircloak/utils
RUN chown deployer:deployer /aircloak/utils

USER deployer

# In order to clone from Github inside the docker image,
# we unfortunately need to relax our host checking...
RUN mkdir -p /home/deployer/.ssh

COPY docker /aircloak/utils

# The source to build
VOLUME /aircloak/source

CMD /aircloak/utils/build.sh
