FROM debian:jessie
MAINTAINER Aircloak

## ------------------------------------------------------------------
## Some basic setup of the image
## ------------------------------------------------------------------

RUN mkdir -p /tmp/build_config && echo '' > /tmp/build_config/proxies.sh
COPY image_shell_init.sh /tmp/build_config/
RUN . /tmp/build_config/image_shell_init.sh
RUN apt-get update && apt-get install openssl liblua5.1-0 libprotobuf-c1 vim nano telnet curl -y

# According to many advices, we'll use gosu instead of sudo to step-down from root
# Apparently, there are some issues with sudo inside the docker container.
RUN . /tmp/build_config/proxies.sh && \
  curl -o /usr/local/bin/gosu -sSL "https://github.com/tianon/gosu/releases/download/1.4/gosu-$(dpkg --print-architecture)" && \
  chmod +x /usr/local/bin/gosu

## ------------------------------------------------------------------
## Create user and copy in app
## ------------------------------------------------------------------

# The erlang app listens to 11000
EXPOSE 11000

# Listening on port 9000 for node connections
EXPOSE 9000

# User under which the app will run.
RUN useradd --create-home --shell /bin/bash deployer && mkdir -p /aircloak/app

WORKDIR /aircloak/app

COPY artifacts/cache/rel/air /aircloak/app
COPY docker/start.sh /aircloak/

RUN chown -R deployer:deployer /aircloak/app && chown -R deployer:deployer /var/run/

# We'll run as root, but step down in the init script to the non-privileged user
USER root

CMD /aircloak/start.sh
