#!/usr/bin/env bash
### BEGIN INIT INFO
# Provides: carbon
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Carbon daemon
# Description: Carbon daemon
### END INIT INFO

prog=carbon
RETVAL=0

start() {
  echo -n $"Starting carbon: "

  PYTHONPATH=/usr/local/lib/python2.7/dist-packages/ /opt/graphite/bin/carbon-cache.py start
  RETVAL=$?

  return $RETVAL
}

stop() {
  echo -n "Stopping carbon: "

  PYTHONPATH=/usr/local/lib/python2.7/dist-packages/ /opt/graphite/bin/carbon-cache.py stop > /dev/null 2>&1
  RETVAL=$?

  return $RETVAL
}

# See how we were called.
case "$1" in
  start)
  start
  ;;
  stop)
  stop
  ;;
  status)
  PYTHONPATH=/usr/local/lib/python2.7/dist-packages/ /opt/graphite/bin/carbon-cache.py status
  RETVAL=$?
  ;;
  restart)
  stop
  start
  ;;
  *)
  echo "Usage: carbon {start|stop|restart|status}"
  exit 1
esac

exit $RETVAL