[template]

# These paths are relative to the confd -confdir parameter
src = "database.tmpl"
dest = "/aircloak/website/config/database.yml"

prefix = "/settings/rails/db"
keys = ["host", "database", "username"]

# Owner and mode should be set to deployer user.
# Unicorn runs as deployer and needs to access
# the configurations.
owner = "deployer"
mode = "0644"
