FROM aircloak/rust:$RUST_VERSION
MAINTAINER Aircloak

ENV CI=true
ENV DEPLOY_CONFIG=dockerized_ci

# Cloak unit tests expect a local mongodb, so we're installing that as well.
RUN \
  apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5 && \
  echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.6 main" | tee /etc/apt/sources.list.d/mongodb-org-3.6.list && \
  apt-get update && \
  apt-get install -y unixodbc odbc-postgresql libmyodbc libaio1 inotify-tools mongodb-org

COPY cloak/priv/odbc/docker/odbc.ini /etc/
COPY cloak/priv/odbc/docker/sqlserver_setup.sh /aircloak/
RUN /aircloak/sqlserver_setup.sh

WORKDIR /aircloak/cloak

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/aircloak/cloak/priv/odbc/drivers/oracle/instantclient_18_3
ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libodbcinst.so

# Oracle locale
ENV NLS_LANG=.AL32UTF8
