FROM aircloak/elixir:$ELIXIR_VERSION
MAINTAINER Aircloak

# Cloak unit tests expect a local mongodb, so we're installing that as well.
RUN \
  apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6 && \
  echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.4 main" | tee /etc/apt/sources.list.d/mongodb-org-3.4.list && \
  apt-get update && \
  apt-get install -y unixodbc odbc-postgresql libmyodbc libaio1 inotify-tools mongodb-org

RUN mkdir -p /data/db/

COPY cloak/priv/odbc/docker/odbc.ini /etc/
COPY cloak/priv/odbc/docker/sqlserver_setup.sh /aircloak/
RUN /aircloak/sqlserver_setup.sh

ENV CI=true
ENV DEPLOY_CONFIG=dockerized_ci
ENV ELIXIR_ERL_OPTIONS="+S 4"

WORKDIR /aircloak/cloak
