CREATE OR REPLACE PACKAGE aircloak AS
  FUNCTION mul(a NUMBER, b NUMBER) RETURN NUMBER DETERMINISTIC;
  FUNCTION mul(a BINARY_DOUBLE, b BINARY_DOUBLE) RETURN BINARY_DOUBLE DETERMINISTIC;
END aircloak;
/

CREATE OR REPLACE PACKAGE BODY aircloak AS
  FUNCTION mul(a NUMBER, b NUMBER) RETURN NUMBER DETERMINISTIC IS
  BEGIN
    RETURN a * b;
  EXCEPTION
    WHEN OTHERS THEN
      RETURN NULL;
  END;

  FUNCTION mul(a BINARY_DOUBLE, b BINARY_DOUBLE) RETURN BINARY_DOUBLE DETERMINISTIC IS
  BEGIN
    RETURN a * b;
  EXCEPTION
    WHEN OTHERS THEN
      RETURN NULL;
  END;
END aircloak;
/
