#!/bin/bash

function setup_port_forward {
  dest_port=$1
  to_port=$2

  if [ "$(iptables-save | egrep '$dest_port 443.*to\-ports $to_port' || echo '')" == "" ]; then
    echo "Setting up forward rule from $dest_port to $to_port"
    iptables -t nat -A PREROUTING -p tcp --dport $dest_port -j REDIRECT --to-port $to_port
  fi
}

old_rules="$(iptables -t nat -S | grep PREROUTING | egrep '\-\-dport (80|443)' || true)"

setup_port_forward 80 20122     # balancer http
setup_port_forward 443 20100    # balancer https

# remove previous rules
if [ "$old_rules" != "" ]; then
  while read line; do
    iptables -t nat $(echo "$line" | sed s/^\-A/-D/)
  done < <(echo "$old_rules")
fi
