defaults: &defaults
  installation:
    global: true
  testing:
    min_cloaks: 3
  task:
    return_host: hello.aircloak.com
  test_server:
    host: test-server.aircloak.com
  build_server:
    host: build.aircloak.com
  log_server:
    host: logserver.aircloak.com
  cloak:
    protocol: https
    port: 443

development:
  <<: *defaults

production:
  <<: *defaults

test: &testing
  <<: *defaults
  task:
    return_host: localhost
  test_server:
    host: localhost
  build_server:
    host: localhost
  log_server:
    host: localhost
