defaults: &defaults
  installation:
    global: true
  testing:
    min_cloaks: 3
  task:
    return_proto: https
    return_host: hello.aircloak.com
    return_port: 443
  test_server:
    host: test-server.aircloak.com
  build_server:
    host: build.aircloak.com
  log_server:
    host: logserver.aircloak.com
  cloak:
    protocol: https
    port: 443
  version_test:
    tpm: false
    enabled: true

development:
  <<: *defaults

production:
  <<: *defaults
  # At the moment we cannot automatically setup
  # non-tpm machines, so we want to run automated
  # tests on our thor hardware
  version_test:
    tpm: true
    enabled: false

test: &testing
  <<: *defaults
  task:
    return_proto: http
    return_host: localhost
    return_port: 3000
  test_server:
    host: localhost
  build_server:
    host: localhost
  log_server:
    host: localhost
