#!/bin/sh -ex

# This script runs all the tests.  It is used by TestServer to perform all tests including the extended PropEr
# tests which are not run on Travis.

old_pwd="$(pwd)"
trap "cd \"$old_pwd\"" EXIT
base_dir="$(dirname "$0")"
cd "$base_dir"

make proper-extended

# These two targets are run by Travis, too.  So we run them after doing proper-extended as that is not done by
# Travis.
# XXX: Disable unit tests for the moment as they cause problems due to timeouts.  As they are run on Travis
#      for each pull, we can live without them on TestServer for the moment.
#make test-eunit
mkdir "$HOME/cloak-plt"
env REBAR_PLT_DIR="$HOME/cloak-plt" "$base_dir/run-dialyzer.sh"
