#!/usr/bin/env bash

source $(dirname $0)/lib/common_functions
source $(dirname $0)/lib/user_management
source $(dirname $0)/lib/packages
source $(dirname $0)/lib/graphite
source $(dirname $0)/lib/iptables

# install and configure
create_user
install_packages
install_graphite
install_init_script carbon
install_init_script graphite_web
grant_permissions

# start the system
/etc/init.d/carbon start
/etc/init.d/graphite_web start
/etc/init.d/nginx start

# Firewall is setup after the machine is provisioned
setup_firewall