#!/usr/bin/env bash

prefix="`dirname $0`/../../test-gen/prefix"

mkdir -p "`dirname "$prefix"`" || exit 1

echo "#!/usr/bin/env escript" > $prefix || exit 1
echo -n "%%! +P 1048576 -hidden -sname proper@localhost -pa .proper" >> $prefix || exit 1
for dep in deps/*
do
  if [ -d $dep/ebin ]
  then
    echo -n " $dep/ebin" >> $prefix || exit 1
  fi
done
echo >> $prefix || exit 1
echo >> $prefix || exit 1
echo "all_modules() ->" >> $prefix || exit 1
echo -n "  [" >> $prefix || exit 1
ls src/*.erl | sed 's,^src/,,' | sed 's,\.erl,,' | awk '{if (n > 0) printf(", %s", $0); else printf("%s", $0); n++}' >> $prefix || exit 1
echo "]." >> $prefix || exit 1
echo >> $prefix || exit 1
