#!/usr/bin/env ruby

# Vagrantfile API/syntax version.
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder "../setup_server", "/setup_server"

  config.vm.box = "Debian 7.3"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/debian-73-x64-virtualbox-nocm.box"

  config.vm.provision "shell", :privileged => true, :inline => <<-SCRIPT
    /setup_server/setup
  SCRIPT

  config.vm.network :forwarded_port, guest: 80, host: 10000
  config.vm.network :forwarded_port, guest: 2003, host: 2003
  config.vm.network :forwarded_port, guest: 2004, host: 2004
end