FROM aircloak/phoenix:$NODEJS_VERSION

RUN \
  echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" >> /etc/apt/sources.list.d/pdgd.list && \
  wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
  apt-get update && \
  apt-get install -y unixodbc odbc-postgresql inotify-tools calibre postgresql-9.6

COPY air/docker/pg_hba.conf /etc/postgresql/9.6/main/
COPY cloak/priv/odbc/odbc.ini /tmp
RUN odbcinst -i -s -h -f /tmp/odbc.ini

# Install Rust
RUN \
  . /tmp/build_config/proxies.sh && \
  echo 'rust $RUST_VERSION' >> ~/.tool-versions && \
  bash -c ". ~/.asdf/asdf.sh && asdf plugin-add rust https://github.com/code-lever/asdf-rust.git" && \
  bash -c ". ~/.asdf/asdf.sh && cd ~ && asdf install"

ENV CI=true
ENV INTEGRATION_TESTS=true
ENV DEPLOY_CONFIG=dockerized_integration

WORKDIR /aircloak/integration_tests
