FROM aircloak/phoenix:$NODEJS_VERSION
MAINTAINER Aircloak

RUN \
  echo "deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main" >> /etc/apt/sources.list.d/pgdg.list && \
  wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
  apt-get update && \
  apt-get install -y unixodbc odbc-postgresql inotify-tools calibre

COPY cloak/priv/odbc/odbc.ini /tmp
RUN odbcinst -i -s -h -f /tmp/odbc.ini

ENV CI=true
ENV INTEGRATION_TESTS=true
ENV DEPLOY_CONFIG=dockerized_integration

WORKDIR /aircloak/integration_tests
