FROM aircloak/phoenix:$NODEJS_VERSION
MAINTAINER Aircloak

# Install dependencies:
# - calibre: needed to compile offline versions of docs
RUN apt-get update && apt-get install -y calibre

ENV CI=true
ENV DEPLOY_CONFIG=dockerized_ci
ENV ELIXIR_ERL_OPTIONS="+S 4"

WORKDIR /aircloak/air
