FROM aircloak/phoenix:$NODEJS_VERSION
MAINTAINER Aircloak

ENV CI=true
ENV DEPLOY_CONFIG=dockerized_ci

# Install dependencies:
# - calibre: needed to compile offline versions of docs
RUN apt-get update && apt-get install -y calibre

WORKDIR /aircloak/air
