#!/usr/bin/env bash

function fetch_source {
  cd /usr/local/src
  git clone https://github.com/graphite-project/graphite-web.git
  cd graphite-web
  git checkout 0.9.12

  cd /usr/local/src
  git clone https://github.com/graphite-project/whisper.git
  cd whisper
  git checkout 0.9.12

  cd /usr/local/src
  git clone https://github.com/graphite-project/carbon.git
  cd carbon
  git checkout 0.9.12
}

function install_apps {
  cd /usr/local/src/graphite-web
  python ./setup.py install

  cd /usr/local/src/whisper-src
  python ./setup.py install

  cd /usr/local/src/carbon
  python ./setup.py install
}

function configure_django_admin {
  chmod +x $(dirname $0)/lib/graphite_syncdb
  $(dirname $0)/lib/graphite_syncdb
}

function configure_carbon {
  mkdir -p /var/log/carbon
  cp /opt/graphite/conf/carbon.conf.example /opt/graphite/conf/carbon.conf
  cp /opt/graphite/conf/storage-schemas.conf.example /opt/graphite/conf/storage-schemas.conf
}

function configure_graphite {
  mkdir -p /var/log/graphite
  copy_asset configuration/local_settings.py /opt/graphite/webapp/graphite/
  copy_asset configuration/carbon.conf /opt/graphite/conf/
  copy_asset configuration/storage-schemas.conf /opt/graphite/conf/
  copy_asset configuration/storage-aggregation.conf /opt/graphite/conf/
}

function configure_nginx {
  mkdir -p /var/log/nginx
  rm /etc/nginx/sites-enabled/default
  copy_asset configuration/graphite_web_server.conf /etc/nginx/sites-available/graphite
  ln -s /etc/nginx/sites-available/graphite /etc/nginx/sites-enabled/graphite
}

function configure_log_rotation {
  copy_asset graphite_logrotate /etc/logrotate.d/graphite
}

function install_graphite {
 fetch_source
 install_apps
 configure_django_admin
 configure_carbon
 configure_graphite
 configure_nginx
 configure_log_rotation
}