#!/usr/bin/env bash

function install_packages {
  apt-get update
  apt-get -y --force-yes install nginx
  apt-get -y --force-yes install python-flup
  apt-get -y --force-yes install expect
  apt-get -y --force-yes install git
  apt-get -y --force-yes install memcached
  apt-get -y --force-yes install sqlite3
  apt-get -y --force-yes install libcairo2
  apt-get -y --force-yes install libcairo2-dev
  apt-get -y --force-yes install python-cairo
  apt-get -y --force-yes install pkg-config
  apt-get -y --force-yes install python-dev
  apt-get -y --force-yes install python-twisted-core
  apt-get -y --force-yes install python-setuptools

  easy_install pip
  pip install django==1.3
  pip install python-memcached==1.53
  pip install django-tagging==0.3.1
  pip install whisper==0.9.12
  pip install twisted==11.1.0
  pip install txAMQP==0.6.2
}