#!/usr/bin/env bash

function create_user {
  useradd graphite_runner
}

function grant_permissions {
  for folder in /var/log/graphite /var/log/carbon /opt/graphite/storage
  do
    mkdir -p $folder
    chown -R graphite_runner $folder
    chmod 755 $folder
  done
}